"""Códigos funcionales estables expuestos por BackendAPI."""

from enum import StrEnum


class ErrorCode(StrEnum):
    """Identificadores estables para errores públicos de la API.

    Los códigos desacoplan a Frontend de los mensajes humanos y de los
    nombres internos de excepciones. El HTTP status conserva la semántica
    del protocolo y ``detail`` conserva el mensaje legible.
    """

    HTTP_ERROR = "HTTP_ERROR"
    BAD_REQUEST = "BAD_REQUEST"

    DOCUMENT_FILENAME_REQUIRED = "DOCUMENT_FILENAME_REQUIRED"
    DOCUMENT_EMPTY = "DOCUMENT_EMPTY"
    DOCUMENT_NOT_FOUND = "DOCUMENT_NOT_FOUND"
    DOCUMENT_STATE_CONFLICT = "DOCUMENT_STATE_CONFLICT"
    DOCUMENT_NOT_INDEXED = "DOCUMENT_NOT_INDEXED"

    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    UNSUPPORTED_FILE_TYPE = "UNSUPPORTED_FILE_TYPE"
    MIME_TYPE_MISMATCH = "MIME_TYPE_MISMATCH"
    REQUEST_VALIDATION_ERROR = "REQUEST_VALIDATION_ERROR"

    DOCUMENT_STORAGE_FAILED = "DOCUMENT_STORAGE_FAILED"
    DOCUMENT_RETRIEVAL_FAILED = "DOCUMENT_RETRIEVAL_FAILED"
    RAG_INDEXING_FAILED = "RAG_INDEXING_FAILED"

    FORMAT_REGISTRATION_FAILED = "FORMAT_REGISTRATION_FAILED"
    FORMAT_REGENERATION_IN_PROGRESS = "FORMAT_REGENERATION_IN_PROGRESS"
    FORMAT_CONTEXT_NOT_FOUND = "FORMAT_CONTEXT_NOT_FOUND"
    FORMAT_CONTEXT_CONFLICT = "FORMAT_CONTEXT_CONFLICT"
    FORMAT_REGENERATION_REGISTRATION_FAILED = (
        "FORMAT_REGENERATION_REGISTRATION_FAILED"
    )

    PERSISTENCE_ERROR = "PERSISTENCE_ERROR"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
